baseURL = "https://alantsehub.pages.dev/"
languageCode = "zh-HK"
title = "AlanTseHub"
theme = "PaperMod"

[params]
  description = "AlanTseHub - 香港新聞、ACG、Vtuber 同隨筆分享"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowToc = true  # 顯示目錄
  isCJKLanguage = true
  homeInfoParams.Title = "AlanTseHub"
  homeInfoParams.Content = "歡迎來到 AlanTseHub！探索香港新聞、ACG、Vtuber 同隨筆！"

[build]
  buildFuture = true

[[menu.main]]
  name = "首頁"
  url = "/"
[[menu.main]]
  name = "新聞 / News"
  url = "/news/"
[[menu.main]]
  name = "動漫遊戲 / ACG"
  url = "/acg/"
[[menu.main]]
  name = "虛擬主播 / Vtuber"
  url = "/vtuber/"
[[menu.main]]
  name = "隨筆 / Blog"
  url = "/blog/"
[[menu.main]]
  name = "資料庫 / Resources"
  url = "/resources/"
[[menu.main]]
  name = "關於我 / About"
  url = "/about/"